baseURL = "https://xqm32.org/"
languageCode = "zh-cn"
title = "Qiming's Blog"
theme = "hugo-xmin"

[[menus.main]]
name = "首页"
pageRef = "/"
weight = 1
[[menus.main]]
name = "关于"
pageRef = "/about"
weight = 2
[[menus.main]]
name = "分类"
pageRef = "/categories"
weight = 3
[[menus.main]]
name = "标签"
pageRef = "/tags"
weight = 4
[[menus.main]]
name = "订阅"
url = "/index.xml"
weight = 5

[markup.goldmark.renderer]
unsafe = true
